baseURL = "http://www.wbprime.me/"
languageCode = "zh"
title = "My Minimal"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Elvis Wang"
    description = "Personal wbprime theme powered by Hugo"
    githubUsername = "#wbprime"
    accent = "blue"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["java", "c++", "go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:mail@wbprime.me"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/wbprime/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.stackoverflow.com/wbprime/"
    name = "stack-overflow"
    weight = 3
