#
# Author: Elvis Wang <mail#wbprime#me>
#

SUBDIRS = # No subdirs

export MARKDOWN_TO_HTML_OPTS := $(MARKDOWN_TO_HTML_OPTS) -c $(WORKING_DIR)/css/panam.css

all: subdirs

clean: clean_subdirs

install: install_subdirs

include $(MAKEINCLUDE)
